const KEY='commissie_tracker_sales_v1';let sales=JSON.parse(localStorage.getItem(KEY)||'[]');let page='dashboard',editing=null,chart=null;
const eur=n=>new Intl.NumberFormat('nl-BE',{style:'currency',currency:'EUR'}).format(Number(n)||0);
const dateBE=s=>{if(!s)return '';const [y,m,d]=s.split('-');return d+'/'+m+'/'+y};
const save=()=>localStorage.setItem(KEY,JSON.stringify(sales));
const monthKey=d=>d?.slice(0,7)||'';const now=new Date();const currentMonth=now.toISOString().slice(0,7);
function totals(list=sales){return{omzet:list.reduce((a,x)=>a+Number(x.price),0),commissie:list.reduce((a,x)=>a+Number(x.commission),0),aantal:list.length}};
function render(){const t=totals();document.getElementById('app').innerHTML=`
<header class="top"><div class="toprow"><div><div class="eyebrow">Sales & Finance</div><div class="brand">Commissie Tracker</div></div><button class="btn gold" onclick="openSale()">+ Verkoop</button></div></header>
<nav class="nav">${[['dashboard','Dashboard'],['sales','Verkopen'],['add','+ Toevoegen'],['stats','Statistieken'],['settings','Instellingen']].map(([k,l])=>`<button class="${page===k?'active ':''}${k==='add'?'add':''}" onclick="${k==='add'?'openSale()':'go(\''+k+'\')'}">${l}</button>`).join('')}</nav>
<main class="content">${page==='dashboard'?dashboard(t):page==='sales'?salesPage():page==='stats'?statsPage():settingsPage()}</main>`;if(page==='stats')drawChart()}
function dashboard(t){const cm=totals(sales.filter(x=>monthKey(x.date)===currentMonth));return`<div class="grid4"><div class="stat"><div class="label">Commissie deze maand</div><div class="value">${eur(cm.commissie)}</div></div><div class="stat"><div class="label">Totale commissie</div><div class="value">${eur(t.commissie)}</div></div><div class="stat"><div class="label">Totale omzet</div><div class="value">${eur(t.omzet)}</div></div><div class="stat"><div class="label">Aantal verkopen</div><div class="value">${t.aantal}</div></div></div><section class="section"><div class="sectionhead"><div class="sectiontitle">Recente verkopen</div><button class="btn ghost" onclick="go('sales')">Alle verkopen</button></div><div class="card">${saleList([...sales].sort((a,b)=>b.date.localeCompare(a.date)).slice(0,6))}</div></section><section class="section"><div class="sectionhead"><div class="sectiontitle">Snel toevoegen</div></div><button class="btn primary" style="width:100%" onclick="openSale()">+ Verkoop toevoegen</button></section>`}
function saleList(list){if(!list.length)return '<div class="empty">Nog geen verkopen toegevoegd.</div>';return '<div class="sales">'+list.map(x=>`<div class="sale"><div class="sale-main"><div class="customer">${esc(x.customer)}</div><div class="meta">${dateBE(x.date)} · ${x.rate}% commissie</div></div><div class="money">${eur(x.price)}<div class="commission">+${eur(x.commission)}</div></div><div class="toolbar"><button class="btn ghost" onclick="openSale('${x.id}')">Bewerk</button><button class="btn danger" onclick="removeSale('${x.id}')">Verwijder</button></div></div>`).join('</div>')}
function salesPage(){let q=document.getElementById('q')?.value||'',mo=document.getElementById('mo')?.value||'',ra=document.getElementById('ra')?.value||'',sort=document.getElementById('sort')?.value||'date';let list=sales.filter(x=>x.customer.toLowerCase().includes(q.toLowerCase())&&(!mo||monthKey(x.date)===mo)&&(!ra||String(x.rate)===ra));list.sort((a,b)=>sort==='price'?Number(b.price)-Number(a.price):b.date.localeCompare(a.date));return`<section><div class="sectionhead"><div><div class="eyebrow">Overzicht</div><div class="sectiontitle">Alle verkopen</div></div><button class="btn primary" onclick="openSale()">+ Toevoegen</button></div><div class="filters"><input id="q" placeholder="Zoek klantnaam..." value="${esc(q)}" oninput="renderSalesOnly()"><input id="mo" type="month" value="${mo}" onchange="renderSalesOnly()"><select id="ra" onchange="renderSalesOnly()"><option value="">Alle percentages</option><option value="8" ${ra==='8'?'selected':''}>8%</option><option value="10" ${ra==='10'?'selected':''}>10%</option><option value="12" ${ra==='12'?'selected':''}>12%</option></select><select id="sort" onchange="renderSalesOnly()"><option value="date" ${sort==='date'?'selected':''}>Nieuwste datum</option><option value="price" ${sort==='price'?'selected':''}>Hoogste verkoopprijs</option></select></div><div id="salescard" class="card">${saleList(list)}</div></section>`}
function renderSalesOnly(){const main=document.querySelector('main');main.innerHTML=salesPage()}
function statsPage(){return`<section><div class="eyebrow">Analyse</div><div class="sectiontitle">Maandoverzicht</div><div class="card section"><div class="chartwrap"><canvas id="chart"></canvas></div></div><div class="card section"><div class="sectiontitle">Maandtotalen</div><div class="sales" style="margin-top:12px">${months().map(m=>{const t=totals(sales.filter(x=>monthKey(x.date)===m.key));return '<div class="sale"><div><div class="customer">'+m.label+'</div><div class="meta">'+t.aantal+' verkopen</div></div><div class="money">'+eur(t.omzet)+'<div class="commission">commissie '+eur(t.commissie)+'</div></div></div>'}).join('')||'<div class="empty">Nog geen gegevens.</div>'}</div></div></section>`}
function months(){const map={};sales.forEach(x=>map[monthKey(x.date)]=1);const keys=Object.keys(map).sort();return keys.map(k=>{const [y,m]=k.split('-');return{key:k,label:new Date(Number(y),Number(m)-1,1).toLocaleDateString('nl-BE',{month:'long',year:'numeric'})}})}
function drawChart(){const labels=months().map(x=>x.label);const omzet=months().map(m=>totals(sales.filter(x=>monthKey(x.date)===m.key)).omzet);const comm=months().map(m=>totals(sales.filter(x=>monthKey(x.date)===m.key)).commissie);const c=document.getElementById('chart');if(!c)return;if(chart)chart.destroy();chart=new Chart(c,{type:'line',data:{labels,datasets:[{label:'Omzet',data:omzet,tension:.35},{label:'Commissie',data:comm,tension:.35}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{position:'bottom'}},scales:{y:{ticks:{callback:v=>'€'+Number(v).toLocaleString('nl-BE')}}}}})}
function settingsPage(){return`<section><div class="eyebrow">Account & data</div><div class="sectiontitle">Instellingen</div><div class="card section"><div class="profile"><div class="avatar">CT</div><div><strong>Mijn profiel</strong><div class="meta">Lokale opslag op dit apparaat</div></div></div></div><div class="settings section"><button class="btn primary" onclick="exportExcel()">Excel-back-up</button><button class="btn ghost" onclick="backup()">Back-up maken</button><button class="btn ghost" onclick="document.getElementById('importFile').click()">Back-up importeren</button><input id="importFile" class="hidden" type="file" accept=".json" onchange="importBackup(event)"><button class="btn danger" onclick="clearAll()">Gegevens verwijderen</button></div><div class="card section"><strong>Opslag</strong><div class="meta">Je gegevens worden automatisch lokaal bewaard, ook wanneer je de app sluit. Voor gebruik op iPhone én Mac is een echte account/cloud-laag nog nodig.</div></div></section>`}
function openSale(id=null){editing=id?sales.find(x=>x.id===id):null;const x=editing||{customer:'',date:now.toISOString().slice(0,10),price:'',rate:10};document.body.insertAdjacentHTML('beforeend',`<div class="modal" id="modal"><div class="modalbox"><div class="modalhead"><div><div class="eyebrow">${editing?'Aanpassen':'Nieuwe verkoop'}</div><div class="sectiontitle">${editing?'Verkoop bewerken':'Verkoop toevoegen'}</div></div><button class="close" onclick="closeModal()">×</button></div><form class="form" onsubmit="submitSale(event,'${editing?.id||''}')"><div class="field"><label>Naam klant</label><input id="customer" required maxlength="100" value="${esc(x.customer)}"></div><div class="field"><label>Datum</label><input id="date" type="date" required value="${x.date}"></div><div class="field"><label>Verkoopprijs (€)</label><input id="price" type="number" min="0.01" step="0.01" required value="${x.price}" oninput="preview()"></div><div class="field"><label>Commissiepercentage</label><select id="rate" onchange="preview()"><option value="8" ${x.rate==8?'selected':''}>8%</option><option value="10" ${x.rate==10?'selected':''}>10%</option><option value="12" ${x.rate==12?'selected':''}>12%</option></select></div><div class="preview">Te ontvangen commissie<br><strong id="commissionPreview">${eur(Number(x.price)*Number(x.rate)/100)}</strong></div><button class="btn primary" type="submit">${editing?'Wijziging opslaan':'Verkoop opslaan'}</button></form></div></div>`);preview()}
function preview(){const p=Number(document.getElementById('price')?.value||0),r=Number(document.getElementById('rate')?.value||0);const el=document.getElementById('commissionPreview');if(el)el.textContent=eur(p*r/100)}
function submitSale(e,id){e.preventDefault();const customer=document.getElementById('customer').value.trim(),date=document.getElementById('date').value,price=Number(document.getElementById('price').value),rate=Number(document.getElementById('rate').value);if(!customer||!date||price<=0||![8,10,12].includes(rate))return toast('Controleer de invoer.');const obj={id:id||crypto.randomUUID(),customer,date,price:Number(price.toFixed(2)),rate,commission:Number((price*rate/100).toFixed(2))};if(id)sales=sales.map(x=>x.id===id?obj:x);else sales.push(obj);save();closeModal();render();toast('Verkoop opgeslagen.')}
function closeModal(){document.getElementById('modal')?.remove();editing=null}
function removeSale(id){if(confirm('Deze verkoop verwijderen?')){sales=sales.filter(x=>x.id!==id);save();render();toast('Verkoop verwijderd.')}}
function clearAll(){if(confirm('Alle verkopen definitief verwijderen?')){sales=[];save();render();toast('Alle gegevens verwijderd.')}}
function backup(){const blob=new Blob([JSON.stringify({version:1,createdAt:new Date().toISOString(),sales},null,2)],{type:'application/json'});download(blob,'Commissie_Back-up_'+new Date().toISOString().slice(0,10)+'.json');toast('Back-up gemaakt.')}
function importBackup(e){const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const d=JSON.parse(r.result);if(!Array.isArray(d.sales))throw 0;if(confirm('Huidige gegevens vervangen door deze back-up?')){sales=d.sales;save();render();toast('Back-up geïmporteerd.')}}catch{toast('Ongeldige back-up.')}};r.readAsText(f)}
function exportExcel(){if(!sales.length){toast('Er zijn nog geen verkopen.');return}const t=totals();const rows=sales.map(x=>({'Naam klant':x.customer,'Datum':dateBE(x.date),'Verkoopprijs':x.price,'Commissie %':x.rate/100,'Commissie €':x.commission}));rows.push({'Naam klant':'TOTAAL','Datum':'','Verkoopprijs':t.omzet,'Commissie %':'','Commissie €':t.commissie});const ws=XLSX.utils.json_to_sheet(rows);ws['!cols']=[{wch:28},{wch:14},{wch:16},{wch:15},{wch:16}];ws['D2'].z='0%';for(let i=2;i<=rows.length;i++)if(ws['D'+i])ws['D'+i].z='0%';for(let i=2;i<=rows.length;i++){if(ws['C'+i])ws['C'+i].z='€ #,##0.00';if(ws['E'+i])ws['E'+i].z='€ #,##0.00'}const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,'Commissie Overzicht');XLSX.writeFile(wb,'Commissie_Overzicht_'+new Date().toISOString().slice(0,10)+'.xlsx');toast('Excel-bestand aangemaakt.')}
function download(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function toast(s){const old=document.querySelector('.toast');old?.remove();document.body.insertAdjacentHTML('beforeend','<div class="toast">'+esc(s)+'</div>');setTimeout(()=>document.querySelector('.toast')?.remove(),2400)}
function go(p){page=p;render()}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
if('serviceWorker' in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});render();